# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter_0 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_0.setOrientation(QtCore.Qt.Vertical)
        self.splitter_0.setObjectName("splitter_0")
        self.top_widget = QtWidgets.QWidget(self.splitter_0)
        self.top_widget.setObjectName("top_widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.top_widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.program_widget = QtWidgets.QWidget(self.top_widget)
        self.program_widget.setObjectName("program_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.program_widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.program_input = QtWidgets.QPlainTextEdit(self.program_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.program_input.setFont(font)
        self.program_input.setAutoFillBackground(False)
        self.program_input.setStyleSheet("")
        self.program_input.setObjectName("program_input")
        self.verticalLayout_6.addWidget(self.program_input)
        self.button_widget = QtWidgets.QWidget(self.program_widget)
        self.button_widget.setObjectName("button_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.button_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.run_step_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.run_step_button.setFont(font)
        self.run_step_button.setObjectName("run_step_button")
        self.horizontalLayout_2.addWidget(self.run_step_button)
        self.run_to_breakpoint_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.run_to_breakpoint_button.setFont(font)
        self.run_to_breakpoint_button.setObjectName("run_to_breakpoint_button")
        self.horizontalLayout_2.addWidget(self.run_to_breakpoint_button)
        self.run_to_end_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.run_to_end_button.setFont(font)
        self.run_to_end_button.setObjectName("run_to_end_button")
        self.horizontalLayout_2.addWidget(self.run_to_end_button)
        self.line_0 = QtWidgets.QFrame(self.button_widget)
        self.line_0.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_0.setObjectName("line_0")
        self.horizontalLayout_2.addWidget(self.line_0)
        self.reset_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.reset_button.setFont(font)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_2.addWidget(self.reset_button)
        self.reset_run_step_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.reset_run_step_button.setFont(font)
        self.reset_run_step_button.setObjectName("reset_run_step_button")
        self.horizontalLayout_2.addWidget(self.reset_run_step_button)
        self.reset_run_to_breakpoint_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.reset_run_to_breakpoint_button.setFont(font)
        self.reset_run_to_breakpoint_button.setObjectName("reset_run_to_breakpoint_button")
        self.horizontalLayout_2.addWidget(self.reset_run_to_breakpoint_button)
        self.reset_run_to_end_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.reset_run_to_end_button.setFont(font)
        self.reset_run_to_end_button.setObjectName("reset_run_to_end_button")
        self.horizontalLayout_2.addWidget(self.reset_run_to_end_button)
        self.line_1 = QtWidgets.QFrame(self.button_widget)
        self.line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.horizontalLayout_2.addWidget(self.line_1)
        self.remove_breakpoints_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.remove_breakpoints_button.setFont(font)
        self.remove_breakpoints_button.setObjectName("remove_breakpoints_button")
        self.horizontalLayout_2.addWidget(self.remove_breakpoints_button)
        self.line_2 = QtWidgets.QFrame(self.button_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.frame_slider = QtWidgets.QSlider(self.button_widget)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.horizontalLayout_2.addWidget(self.frame_slider)
        self.frame_down_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.frame_down_button.setFont(font)
        self.frame_down_button.setObjectName("frame_down_button")
        self.horizontalLayout_2.addWidget(self.frame_down_button)
        self.frame_up_button = QtWidgets.QToolButton(self.button_widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.frame_up_button.setFont(font)
        self.frame_up_button.setObjectName("frame_up_button")
        self.horizontalLayout_2.addWidget(self.frame_up_button)
        self.verticalLayout_6.addWidget(self.button_widget)
        self.horizontalLayout_6.addWidget(self.program_widget)
        self.table_widget = QtWidgets.QWidget(self.top_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_widget.sizePolicy().hasHeightForWidth())
        self.table_widget.setSizePolicy(sizePolicy)
        self.table_widget.setObjectName("table_widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.table_widget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.status_table = QtWidgets.QTableWidget(self.table_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_table.sizePolicy().hasHeightForWidth())
        self.status_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.status_table.setFont(font)
        self.status_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.status_table.setShowGrid(True)
        self.status_table.setGridStyle(QtCore.Qt.SolidLine)
        self.status_table.setObjectName("status_table")
        self.status_table.setColumnCount(2)
        self.status_table.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status_table.setItem(10, 1, item)
        self.status_table.horizontalHeader().setVisible(True)
        self.status_table.horizontalHeader().setSortIndicatorShown(False)
        self.status_table.horizontalHeader().setStretchLastSection(True)
        self.status_table.verticalHeader().setVisible(False)
        self.status_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_8.addWidget(self.status_table)
        self.horizontalLayout_6.addWidget(self.table_widget)
        self.bottom_widget = QtWidgets.QWidget(self.splitter_0)
        self.bottom_widget.setObjectName("bottom_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bottom_widget)
        self.verticalLayout_3.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_1 = QtWidgets.QSplitter(self.bottom_widget)
        self.splitter_1.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_1.setObjectName("splitter_1")
        self.inputs_widget = QtWidgets.QWidget(self.splitter_1)
        self.inputs_widget.setObjectName("inputs_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inputs_widget)
        self.verticalLayout.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputs_tabs = QtWidgets.QTabWidget(self.inputs_widget)
        self.inputs_tabs.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.inputs_tabs.setFont(font)
        self.inputs_tabs.setObjectName("inputs_tabs")
        self.console_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_tab.sizePolicy().hasHeightForWidth())
        self.console_tab.setSizePolicy(sizePolicy)
        self.console_tab.setObjectName("console_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.console_tab)
        self.verticalLayout_4.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.console_output = QtWidgets.QTextBrowser(self.console_tab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.console_output.setFont(font)
        self.console_output.setObjectName("console_output")
        self.verticalLayout_4.addWidget(self.console_output)
        self.console_buttons = QtWidgets.QWidget(self.console_tab)
        self.console_buttons.setObjectName("console_buttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.console_buttons)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.console_input = QtWidgets.QLineEdit(self.console_buttons)
        self.console_input.setEnabled(True)
        self.console_input.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.console_input.setFont(font)
        self.console_input.setObjectName("console_input")
        self.horizontalLayout_4.addWidget(self.console_input)
        self.console_blocked = QtQuickWidgets.QQuickWidget(self.console_buttons)
        self.console_blocked.setMinimumSize(QtCore.QSize(16, 0))
        self.console_blocked.setObjectName("console_blocked")
        self.horizontalLayout_4.addWidget(self.console_blocked)
        self.console_input_value = QtWidgets.QLabel(self.console_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_input_value.sizePolicy().hasHeightForWidth())
        self.console_input_value.setSizePolicy(sizePolicy)
        self.console_input_value.setMinimumSize(QtCore.QSize(36, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.console_input_value.setFont(font)
        self.console_input_value.setObjectName("console_input_value")
        self.horizontalLayout_4.addWidget(self.console_input_value)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.console_enter_button = QtWidgets.QPushButton(self.console_buttons)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.console_enter_button.setFont(font)
        self.console_enter_button.setObjectName("console_enter_button")
        self.horizontalLayout_4.addWidget(self.console_enter_button)
        self.console_reset_button = QtWidgets.QPushButton(self.console_buttons)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.console_reset_button.setFont(font)
        self.console_reset_button.setObjectName("console_reset_button")
        self.horizontalLayout_4.addWidget(self.console_reset_button)
        self.console_enable = QtWidgets.QCheckBox(self.console_buttons)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.console_enable.setFont(font)
        self.console_enable.setObjectName("console_enable")
        self.horizontalLayout_4.addWidget(self.console_enable)
        self.verticalLayout_4.addWidget(self.console_buttons)
        self.inputs_tabs.addTab(self.console_tab, "")
        self.modem_tab = QtWidgets.QWidget()
        self.modem_tab.setObjectName("modem_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.modem_tab)
        self.verticalLayout_9.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.modem_output = QtWidgets.QTextBrowser(self.modem_tab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.modem_output.setFont(font)
        self.modem_output.setObjectName("modem_output")
        self.verticalLayout_9.addWidget(self.modem_output)
        self.modem_buttons = QtWidgets.QWidget(self.modem_tab)
        self.modem_buttons.setObjectName("modem_buttons")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.modem_buttons)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.modem_input = QtWidgets.QLineEdit(self.modem_buttons)
        self.modem_input.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.modem_input.setFont(font)
        self.modem_input.setObjectName("modem_input")
        self.horizontalLayout_5.addWidget(self.modem_input)
        self.modem_blocked = QtQuickWidgets.QQuickWidget(self.modem_buttons)
        self.modem_blocked.setMinimumSize(QtCore.QSize(16, 0))
        self.modem_blocked.setObjectName("modem_blocked")
        self.horizontalLayout_5.addWidget(self.modem_blocked)
        self.modem_input_value = QtWidgets.QLabel(self.modem_buttons)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.modem_input_value.setFont(font)
        self.modem_input_value.setObjectName("modem_input_value")
        self.horizontalLayout_5.addWidget(self.modem_input_value)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.modem_enter_button = QtWidgets.QPushButton(self.modem_buttons)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.modem_enter_button.setFont(font)
        self.modem_enter_button.setObjectName("modem_enter_button")
        self.horizontalLayout_5.addWidget(self.modem_enter_button)
        self.modem_reset_button = QtWidgets.QPushButton(self.modem_buttons)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.modem_reset_button.setFont(font)
        self.modem_reset_button.setObjectName("modem_reset_button")
        self.horizontalLayout_5.addWidget(self.modem_reset_button)
        self.modem_enable = QtWidgets.QCheckBox(self.modem_buttons)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.modem_enable.setFont(font)
        self.modem_enable.setObjectName("modem_enable")
        self.horizontalLayout_5.addWidget(self.modem_enable)
        self.verticalLayout_9.addWidget(self.modem_buttons)
        self.inputs_tabs.addTab(self.modem_tab, "")
        self.verticalLayout.addWidget(self.inputs_tabs)
        self.outputs_widget = QtWidgets.QWidget(self.splitter_1)
        self.outputs_widget.setMinimumSize(QtCore.QSize(578, 0))
        self.outputs_widget.setObjectName("outputs_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.outputs_widget)
        self.verticalLayout_2.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputs_tabs = QtWidgets.QTabWidget(self.outputs_widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.outputs_tabs.setFont(font)
        self.outputs_tabs.setObjectName("outputs_tabs")
        self.memory_tab = QtWidgets.QWidget()
        self.memory_tab.setObjectName("memory_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.memory_tab)
        self.gridLayout_2.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.memory_buffer = QtWidgets.QTextBrowser(self.memory_tab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.memory_buffer.setFont(font)
        self.memory_buffer.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.memory_buffer.setObjectName("memory_buffer")
        self.gridLayout_2.addWidget(self.memory_buffer, 0, 0, 1, 1)
        self.memory_buttons = QtWidgets.QWidget(self.memory_tab)
        self.memory_buttons.setObjectName("memory_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.memory_buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.memory_select = QtWidgets.QComboBox(self.memory_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memory_select.sizePolicy().hasHeightForWidth())
        self.memory_select.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.memory_select.setFont(font)
        self.memory_select.setObjectName("memory_select")
        self.memory_select.addItem("")
        self.memory_select.addItem("")
        self.memory_select.addItem("")
        self.horizontalLayout.addWidget(self.memory_select)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.memory_address = QtWidgets.QSpinBox(self.memory_buttons)
        self.memory_address.setObjectName("memory_address")
        self.horizontalLayout.addWidget(self.memory_address)
        self.memory_input = QtWidgets.QLineEdit(self.memory_buttons)
        self.memory_input.setObjectName("memory_input")
        self.horizontalLayout.addWidget(self.memory_input)
        self.memory_equal_button = QtWidgets.QToolButton(self.memory_buttons)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.memory_equal_button.setFont(font)
        self.memory_equal_button.setObjectName("memory_equal_button")
        self.horizontalLayout.addWidget(self.memory_equal_button)
        self.memory_zero_button = QtWidgets.QToolButton(self.memory_buttons)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.memory_zero_button.setFont(font)
        self.memory_zero_button.setObjectName("memory_zero_button")
        self.horizontalLayout.addWidget(self.memory_zero_button)
        self.line = QtWidgets.QFrame(self.memory_buttons)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.memory_zero_all_button = QtWidgets.QToolButton(self.memory_buttons)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.memory_zero_all_button.setFont(font)
        self.memory_zero_all_button.setObjectName("memory_zero_all_button")
        self.horizontalLayout.addWidget(self.memory_zero_all_button)
        self.gridLayout_2.addWidget(self.memory_buttons, 1, 0, 1, 1)
        self.outputs_tabs.addTab(self.memory_tab, "")
        self.io_tab = QtWidgets.QWidget()
        self.io_tab.setObjectName("io_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.io_tab)
        self.gridLayout_3.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.io_buttons = QtWidgets.QWidget(self.io_tab)
        self.io_buttons.setObjectName("io_buttons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.io_buttons)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buffer_select = QtWidgets.QComboBox(self.io_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buffer_select.sizePolicy().hasHeightForWidth())
        self.buffer_select.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.buffer_select.setFont(font)
        self.buffer_select.setObjectName("buffer_select")
        self.buffer_select.addItem("")
        self.buffer_select.addItem("")
        self.buffer_select.addItem("")
        self.horizontalLayout_3.addWidget(self.buffer_select)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.buffer_address = QtWidgets.QSpinBox(self.io_buttons)
        self.buffer_address.setObjectName("buffer_address")
        self.horizontalLayout_3.addWidget(self.buffer_address)
        self.buffer_input = QtWidgets.QLineEdit(self.io_buttons)
        self.buffer_input.setObjectName("buffer_input")
        self.horizontalLayout_3.addWidget(self.buffer_input)
        self.buffer_equal_button = QtWidgets.QToolButton(self.io_buttons)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.buffer_equal_button.setFont(font)
        self.buffer_equal_button.setObjectName("buffer_equal_button")
        self.horizontalLayout_3.addWidget(self.buffer_equal_button)
        self.buffer_zero_button = QtWidgets.QToolButton(self.io_buttons)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.buffer_zero_button.setFont(font)
        self.buffer_zero_button.setObjectName("buffer_zero_button")
        self.horizontalLayout_3.addWidget(self.buffer_zero_button)
        self.line_3 = QtWidgets.QFrame(self.io_buttons)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.buffer_zero_all_button = QtWidgets.QToolButton(self.io_buttons)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.buffer_zero_all_button.setFont(font)
        self.buffer_zero_all_button.setObjectName("buffer_zero_all_button")
        self.horizontalLayout_3.addWidget(self.buffer_zero_all_button)
        self.gridLayout_3.addWidget(self.io_buttons, 1, 0, 1, 1)
        self.io_buffer = QtWidgets.QTextBrowser(self.io_tab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.io_buffer.setFont(font)
        self.io_buffer.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.io_buffer.setObjectName("io_buffer")
        self.gridLayout_3.addWidget(self.io_buffer, 0, 0, 1, 1)
        self.io_buffer.raise_()
        self.io_buttons.raise_()
        self.outputs_tabs.addTab(self.io_tab, "")
        self.log_tab = QtWidgets.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.log_tab)
        self.gridLayout_4.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.log_buttons = QtWidgets.QWidget(self.log_tab)
        self.log_buttons.setObjectName("log_buttons")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.log_buttons)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.log_level = QtWidgets.QComboBox(self.log_buttons)
        self.log_level.setObjectName("log_level")
        self.log_level.addItem("")
        self.log_level.addItem("")
        self.log_level.addItem("")
        self.log_level.addItem("")
        self.log_level.addItem("")
        self.horizontalLayout_7.addWidget(self.log_level)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.log_reset_button = QtWidgets.QToolButton(self.log_buttons)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.log_reset_button.setFont(font)
        self.log_reset_button.setObjectName("log_reset_button")
        self.horizontalLayout_7.addWidget(self.log_reset_button)
        self.gridLayout_4.addWidget(self.log_buttons, 1, 0, 1, 1)
        self.log_buffer = QtWidgets.QTextBrowser(self.log_tab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.log_buffer.setFont(font)
        self.log_buffer.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.log_buffer.setObjectName("log_buffer")
        self.gridLayout_4.addWidget(self.log_buffer, 0, 0, 1, 1)
        self.outputs_tabs.addTab(self.log_tab, "")
        self.verticalLayout_2.addWidget(self.outputs_tabs)
        self.verticalLayout_3.addWidget(self.splitter_1)
        self.verticalLayout_5.addWidget(self.splitter_0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRecent = QtWidgets.QAction(MainWindow)
        self.actionRecent.setObjectName("actionRecent")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRecent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.inputs_tabs.setCurrentIndex(0)
        self.outputs_tabs.setCurrentIndex(0)
        self.memory_select.setCurrentIndex(2)
        self.buffer_select.setCurrentIndex(2)
        self.log_level.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.run_step_button.setToolTip(_translate("MainWindow", "Run one step"))
        self.run_step_button.setText(_translate("MainWindow", ">"))
        self.run_to_breakpoint_button.setToolTip(_translate("MainWindow", "Run to breakpoint"))
        self.run_to_breakpoint_button.setText(_translate("MainWindow", ">|"))
        self.run_to_end_button.setToolTip(_translate("MainWindow", "Run to end"))
        self.run_to_end_button.setText(_translate("MainWindow", ">>"))
        self.reset_button.setToolTip(_translate("MainWindow", "Reset"))
        self.reset_button.setText(_translate("MainWindow", "<0"))
        self.reset_run_step_button.setToolTip(_translate("MainWindow", "Reset; Run one step"))
        self.reset_run_step_button.setText(_translate("MainWindow", "0>"))
        self.reset_run_to_breakpoint_button.setToolTip(_translate("MainWindow", "Reset; Run to breakpoint"))
        self.reset_run_to_breakpoint_button.setText(_translate("MainWindow", "0>|"))
        self.reset_run_to_end_button.setToolTip(_translate("MainWindow", "Reset; Run to end"))
        self.reset_run_to_end_button.setText(_translate("MainWindow", "0>>"))
        self.remove_breakpoints_button.setToolTip(_translate("MainWindow", "Remove breakpoints"))
        self.remove_breakpoints_button.setText(_translate("MainWindow", "x|"))
        self.frame_slider.setToolTip(_translate("MainWindow", "Select frame"))
        self.frame_down_button.setToolTip(_translate("MainWindow", "Back one frame"))
        self.frame_down_button.setText(_translate("MainWindow", "-"))
        self.frame_up_button.setToolTip(_translate("MainWindow", "Ahead one frame"))
        self.frame_up_button.setText(_translate("MainWindow", "+"))
        item = self.status_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.status_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.status_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.status_table.isSortingEnabled()
        self.status_table.setSortingEnabled(False)
        item = self.status_table.item(0, 0)
        item.setText(_translate("MainWindow", "frame"))
        item = self.status_table.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.status_table.item(1, 0)
        item.setText(_translate("MainWindow", "stack_depth"))
        item = self.status_table.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.status_table.item(2, 0)
        item.setText(_translate("MainWindow", "eptr"))
        item = self.status_table.item(2, 1)
        item.setText(_translate("MainWindow", "NONE"))
        item = self.status_table.item(3, 0)
        item.setText(_translate("MainWindow", "mptr"))
        item = self.status_table.item(3, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.status_table.item(4, 0)
        item.setText(_translate("MainWindow", "operator"))
        item = self.status_table.item(4, 1)
        item.setText(_translate("MainWindow", "+"))
        item = self.status_table.item(5, 0)
        item.setText(_translate("MainWindow", "icell_len"))
        item = self.status_table.item(5, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.status_table.item(6, 0)
        item.setText(_translate("MainWindow", "imode"))
        item = self.status_table.item(6, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.status_table.item(7, 0)
        item.setText(_translate("MainWindow", "in_dead_loop"))
        item = self.status_table.item(7, 1)
        item.setText(_translate("MainWindow", "False"))
        item = self.status_table.item(8, 0)
        item.setText(_translate("MainWindow", "loop_depth"))
        item = self.status_table.item(8, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.status_table.item(9, 0)
        item.setText(_translate("MainWindow", "loop_ptr"))
        item = self.status_table.item(9, 1)
        item.setText(_translate("MainWindow", "None"))
        item = self.status_table.item(10, 0)
        item.setText(_translate("MainWindow", "goto"))
        item = self.status_table.item(10, 1)
        item.setText(_translate("MainWindow", "None"))
        self.status_table.setSortingEnabled(__sortingEnabled)
        self.console_input_value.setText(_translate("MainWindow", "None"))
        self.console_enter_button.setText(_translate("MainWindow", "Enter"))
        self.console_reset_button.setText(_translate("MainWindow", "Reset"))
        self.console_enable.setText(_translate("MainWindow", "On"))
        self.inputs_tabs.setTabText(self.inputs_tabs.indexOf(self.console_tab), _translate("MainWindow", "Console"))
        self.modem_input_value.setText(_translate("MainWindow", "None"))
        self.modem_enter_button.setText(_translate("MainWindow", "Enter"))
        self.modem_reset_button.setText(_translate("MainWindow", "Reset"))
        self.modem_enable.setText(_translate("MainWindow", "On"))
        self.inputs_tabs.setTabText(self.inputs_tabs.indexOf(self.modem_tab), _translate("MainWindow", "Modem"))
        self.memory_select.setToolTip(_translate("MainWindow", "Memory Format"))
        self.memory_select.setItemText(0, _translate("MainWindow", "Ascii"))
        self.memory_select.setItemText(1, _translate("MainWindow", "Hex"))
        self.memory_select.setItemText(2, _translate("MainWindow", "Int"))
        self.memory_equal_button.setText(_translate("MainWindow", "="))
        self.memory_zero_button.setText(_translate("MainWindow", "0"))
        self.memory_zero_all_button.setText(_translate("MainWindow", "00"))
        self.outputs_tabs.setTabText(self.outputs_tabs.indexOf(self.memory_tab), _translate("MainWindow", "Memory"))
        self.buffer_select.setToolTip(_translate("MainWindow", "IO Buffer Format"))
        self.buffer_select.setItemText(0, _translate("MainWindow", "Ascii"))
        self.buffer_select.setItemText(1, _translate("MainWindow", "Hex"))
        self.buffer_select.setItemText(2, _translate("MainWindow", "Int"))
        self.buffer_equal_button.setText(_translate("MainWindow", "="))
        self.buffer_zero_button.setText(_translate("MainWindow", "0"))
        self.buffer_zero_all_button.setText(_translate("MainWindow", "00"))
        self.outputs_tabs.setTabText(self.outputs_tabs.indexOf(self.io_tab), _translate("MainWindow", "IO Buffer"))
        self.log_level.setItemText(0, _translate("MainWindow", "Debug"))
        self.log_level.setItemText(1, _translate("MainWindow", "Info"))
        self.log_level.setItemText(2, _translate("MainWindow", "Warning"))
        self.log_level.setItemText(3, _translate("MainWindow", "Error"))
        self.log_level.setItemText(4, _translate("MainWindow", "Critical"))
        self.log_reset_button.setText(_translate("MainWindow", "Reset"))
        self.outputs_tabs.setTabText(self.outputs_tabs.indexOf(self.log_tab), _translate("MainWindow", "TBAS Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionRecent.setText(_translate("MainWindow", "Recent"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))

from PyQt5 import QtQuickWidgets
